--------------------------------------------------------------------------------------------------------------------------------
-- AGREGAMOS LOS CAMPOS NECESARIOS EN LA TABLA GESTION_CENTROS.PC_DELEGACIONES_DETALLES
--------------------------------------------------------------------------------------------------------------------------------

--GASTO_COMUNIDAD
ALTER TABLE GESTION_CENTROS.PC_DELEGACIONES_DETALLES ADD GASTO_COMUNIDAD NUMERIC;

--ALARMA_ROBO
ALTER TABLE GESTION_CENTROS.PC_DELEGACIONES_DETALLES ADD ALARMA_ROBO BOOLEAN SET DEFAULT FALSE;

--ALARMA_INCENDIO
ALTER TABLE GESTION_CENTROS.PC_DELEGACIONES_DETALLES ADD ALARMA_INCENDIO BOOLEAN SET DEFAULT FALSE;



------------------------------------------------------------------------------------------------------------------------
-- TABLE GESTION_CENTROS.TM_DOC_GENERAL_TIPOS
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE GESTION_CENTROS.TM_DOC_GENERAL_TIPOS (
ID BIGINT NOT NULL,
DENOMINACION VARCHAR(100) NOT NULL,
OBSERVACIONES VARCHAR(200),
ACTIVO BOOLEAN NOT NULL,
CONSTRAINT TM_DOC_GENERAL_TIPOS_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.TM_DOC_GENERAL_TIPOS.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.TM_DOC_GENERAL_TIPOS.DENOMINACION IS 'Denominación del documentación general';
COMMENT ON COLUMN GESTION_CENTROS.TM_DOC_GENERAL_TIPOS.OBSERVACIONES IS 'Observaciones sobre el tipo de documentación general';
COMMENT ON COLUMN GESTION_CENTROS.TM_DOC_GENERAL_TIPOS.ACTIVO IS 'False - No activo, True -  Activo';



------------------------------------------------------------------------------------------------------------------------
-- TABLE GESTION_CENTROS.TM_CERTIFICADOS
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE GESTION_CENTROS.TM_CERTIFICADOS (
ID BIGINT NOT NULL,
DENOMINACION VARCHAR(100) NOT NULL,
OBSERVACIONES VARCHAR(200),
ACTIVO BOOLEAN NOT NULL,
CONSTRAINT TM_CERTIFICADOS_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.TM_CERTIFICADOS.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.TM_CERTIFICADOS.DENOMINACION IS 'Denominación del tipo de certificado';
COMMENT ON COLUMN GESTION_CENTROS.TM_CERTIFICADOS.OBSERVACIONES IS 'Observaciones sobre el tipo de certificado';
COMMENT ON COLUMN GESTION_CENTROS.TM_CERTIFICADOS.ACTIVO IS 'False - No activo, True -  Activo';



------------------------------------------------------------------------------------------------------------------------
-- TABLE GESTION_CENTROS.TM_IMPUESTOS
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE GESTION_CENTROS.TM_IMPUESTOS (
ID BIGINT NOT NULL,
DENOMINACION VARCHAR(100) NOT NULL,
OBSERVACIONES VARCHAR(200),
ACTIVO BOOLEAN NOT NULL,
CONSTRAINT TM_IMPUESTOS_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.TM_IMPUESTOS.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.TM_IMPUESTOS.DENOMINACION IS 'Denominación del tipo de impuesto';
COMMENT ON COLUMN GESTION_CENTROS.TM_IMPUESTOS.OBSERVACIONES IS 'Observaciones sobre el tipo de impuesto';
COMMENT ON COLUMN GESTION_CENTROS.TM_IMPUESTOS.ACTIVO IS 'False - No activo, True -  Activo';



------------------------------------------------------------------------------------------------------------------------
-- TABLE GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL (
ID BIGINT NOT NULL,
TIPO_DOCUMENTO_ID BIGINT NOT NULL,
DELEGACION_ID BIGINT NOT NULL,
NOMBRE VARCHAR(200),
IMPORTE NUMERIC(10,2),
FECHA_INICIO DATE,
FECHA_FIN DATE,
FECHA_PREAVISO DATE,
OBSERVACIONES VARCHAR(2000),
NOMBRE_ASEGURADORA VARCHAR(100),
NUMERO_POLIZA VARCHAR(80),
MEDIDADOR VARCHAR(100),
TELEFONO VARCHAR(15),
EMAIL VARCHAR(150),
IMPORTE_ANUAL NUMERIC(10,2),
PERIODICIDAD_GASTO_ID BIGINT,
DEPOSITO NUMERIC(10,2),
CERTIFICADO_ID BIGINT,
IMPUESTO_ID BIGINT,
CREADO TIMESTAMP NOT NULL,
CREADO_POR BIGINT NOT NULL,
MODIFICADO TIMESTAMP,
MODIFICADO_POR BIGINT,
BORRADO TIMESTAMP,
BORRADO_POR BIGINT,
CONSTRAINT PC_DELEGACIONES_X_DOC_GENERAL_PK PRIMARY KEY (ID),
FOREIGN KEY (TIPO_DOCUMENTO_ID) REFERENCES GESTION_CENTROS.TM_DOC_GENERAL_TIPOS (ID),
FOREIGN KEY (DELEGACION_ID) REFERENCES GC2006_RELEASE.PC_DELEGACIONES (ID),
FOREIGN KEY (PERIODICIDAD_GASTO_ID) REFERENCES GESTION_CENTROS.TM_PERIODICIDAD_GASTO (ID),
FOREIGN KEY (CERTIFICADO_ID) REFERENCES GESTION_CENTROS.TM_CERTIFICADOS (ID),
FOREIGN KEY (IMPUESTO_ID) REFERENCES GESTION_CENTROS.TM_IMPUESTOS (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.TIPO_DOCUMENTO_ID IS 'FK: GESTION_CENTROS.TM_DOC_GENERAL_TIPOS.ID';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.DELEGACION_ID IS 'FK: GC2006_RELEASE.PC_DELEGACIONES.ID';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.NOMBRE IS 'Nombre de la documentación';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.IMPORTE IS 'Importe del tipo de documentación';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.FECHA_INICIO IS 'Fecha inicio de la documentación';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.FECHA_FIN IS 'Fecha fin de la documentación';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.FECHA_FIN IS 'Fecha de preaviso de la documentación';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.OBSERVACIONES IS 'Observaciones de la documentación';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.NOMBRE_ASEGURADORA IS 'Nombre de la aseguradora en caso de ser tipo ‘Seguro local’';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.NUMERO_POLIZA IS 'Número de la póliza en caso de ser ‘Seguro local’';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.MEDIDADOR IS 'Persona mediadora en caso de ser ‘Seguro local’';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.TELEFONO IS 'Teléfono del mediador en caso de ser ‘Seguro local’';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.EMAIL IS 'Email del mediador en caso de ser ‘Seguro local’';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.IMPORTE_ANUAL IS 'Importe anual del tipo de documentación';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.PERIODICIDAD_GASTO_ID IS 'FK: GESTION_CENTROS.TM_PERIOCIDIDAD_GASTO.ID';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.DEPOSITO IS 'Depósito del tipo de documentación';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.CERTIFICADO_ID IS 'FK: GESTION_CENTROS.TM_CERTIFICADOS_TIPOS.ID';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.IMPUESTO_ID IS 'FK: GESTION_CENTROS.TM_IMPUESTOS_TIPOS.ID';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.CREADO IS 'Fecha de creación de los detalles del centro';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.CREADO_POR IS 'FK: GC2006_RELEASE.PC_USUARIOS.ID';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.MODIFICADO IS 'Fecha de modificación de la documentación general';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.MODIFICADO_POR IS 'FK: GC2006_RELEASE.PC_USUARIOS.ID';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.BORRADO IS 'Fecha de borrado de la documentación general';
COMMENT ON COLUMN GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.BORRADO_POR IS 'FK: GC2006_RELEASE.PC_USUARIOS.ID';


CREATE SEQUENCE GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL_SEQ
MINVALUE 1
MAXVALUE 9999999999999999
INCREMENT BY 1;



------------------------------------------------------------------------------------------------------------------------
-- TABLE GESTION_CENTROS.DOC_GENERAL_X_ADJUNTOS
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE GESTION_CENTROS.DOC_GENERAL_X_ADJUNTOS (
ID BIGINT NOT NULL,
DOC_GENERAL_ID BIGINT NOT NULL,
DOC_URL VARCHAR(200) NOT NULL,
DOC_NOMBRE VARCHAR(150) NOT NULL,
DOC_CONTENT_TYPE VARCHAR(100) NOT NULL,
CONSTRAINT DOC_GENERAL_X_ADJUNTOS_PK PRIMARY KEY (ID),
FOREIGN KEY (DOC_GENERAL_ID) REFERENCES GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.DOC_GENERAL_X_ADJUNTOS.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.DOC_GENERAL_X_ADJUNTOS.DOC_GENERAL_ID IS 'FK: GESTION_CENTROS.PC_DELEGACIONES_X_DOC_GENERAL.ID';
COMMENT ON COLUMN GESTION_CENTROS.DOC_GENERAL_X_ADJUNTOS.DOC_URL IS 'URL donde se almacena el fichero';
COMMENT ON COLUMN GESTION_CENTROS.DOC_GENERAL_X_ADJUNTOS.DOC_NOMBRE IS 'Nombre del fichero';
COMMENT ON COLUMN GESTION_CENTROS.DOC_GENERAL_X_ADJUNTOS.DOC_CONTENT_TYPE IS 'Content type del fichero';


CREATE SEQUENCE GESTION_CENTROS.DOC_GENERAL_X_ADJUNTOS_SEQ
MINVALUE 1
MAXVALUE 9999999999999999
INCREMENT BY 1;



------------------------------------------------------------------------------------------------------------------------
-- TABLE GESTION_CENTROS.PLANOS_X_ADJUNTOS
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE GESTION_CENTROS.PLANOS_X_ADJUNTOS (
ID BIGINT NOT NULL,
PLANO_ID BIGINT NOT NULL,
DOC_URL VARCHAR(200) NOT NULL,
DOC_NOMBRE VARCHAR(150) NOT NULL,
DOC_CONTENT_TYPE VARCHAR(100) NOT NULL,
CONSTRAINT PLANOS_X_ADJUNTOS_PK PRIMARY KEY (ID),
FOREIGN KEY (PLANO_ID) REFERENCES GESTION_CENTROS.PC_DELEGACIONES_X_PLANOS (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.PLANOS_X_ADJUNTOS.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.PLANOS_X_ADJUNTOS.PLANO_ID IS 'FK: GESTION_CENTROS.PC_DELEGACIONES_X_PLANOS.ID';
COMMENT ON COLUMN GESTION_CENTROS.PLANOS_X_ADJUNTOS.DOC_URL IS 'URL donde se almacena el fichero';
COMMENT ON COLUMN GESTION_CENTROS.PLANOS_X_ADJUNTOS.DOC_NOMBRE IS 'Nombre del fichero';
COMMENT ON COLUMN GESTION_CENTROS.PLANOS_X_ADJUNTOS.DOC_CONTENT_TYPE IS 'Content type del fichero';


CREATE SEQUENCE GESTION_CENTROS.PLANOS_X_ADJUNTOS_SEQ
MINVALUE 1
MAXVALUE 9999999999999999
INCREMENT BY 1;



------------------------------------------------------------------------------------------------------------------------
-- Insert data
------------------------------------------------------------------------------------------------------------------------
-- GESTION_CENTROS.TM_DOC_GENERAL_TIPOS
INSERT INTO GESTION_CENTROS.TM_DOC_GENERAL_TIPOS (id, denominacion, observaciones, activo)
VALUES (1, 'CONTRATO ALQUILER', '', true);

INSERT INTO GESTION_CENTROS.TM_DOC_GENERAL_TIPOS (id, denominacion, observaciones, activo)
VALUES (2, 'SEGURO LOCAL', '', true);

INSERT INTO GESTION_CENTROS.TM_DOC_GENERAL_TIPOS (id, denominacion, observaciones, activo)
VALUES (3, 'IMPUESTO', '', true);

INSERT INTO GESTION_CENTROS.TM_DOC_GENERAL_TIPOS (id, denominacion, observaciones, activo)
VALUES (4, 'LICENCIA/CERTIFICACION', '', true);


-- GESTION_CENTROS.TM_CERTIFICADOS
INSERT INTO GESTION_CENTROS.TM_CERTIFICADOS (id, denominacion, observaciones, activo)
VALUES (1, 'CERTIFICADO', '', true);

INSERT INTO GESTION_CENTROS.TM_CERTIFICADOS (id, denominacion, observaciones, activo)
VALUES (2, 'LICENCIA APERTURA', '', true);

INSERT INTO GESTION_CENTROS.TM_CERTIFICADOS (id, denominacion, observaciones, activo)
VALUES (3, 'ACREDITACIÓN SANITARIA', '', true);


-- GESTION_CENTROS.TM_IMPUESTOS
INSERT INTO GESTION_CENTROS.TM_IMPUESTOS (id, denominacion, observaciones, activo)
VALUES (1, 'IBI', '', true);

INSERT INTO GESTION_CENTROS.TM_IMPUESTOS (id, denominacion, observaciones, activo)
VALUES (2, 'I.A.E.', '', true);


-- NEW FIELDS WORK CENTERS DETAILS
ALTER TABLE GESTION_CENTROS.PC_DELEGACIONES_DETALLES ADD COLUMN REF_CATASTRAL VARCHAR(50);
ALTER TABLE GESTION_CENTROS.PC_DELEGACIONES_DETALLES ADD COLUMN LATITUD VARCHAR(20);
ALTER TABLE GESTION_CENTROS.PC_DELEGACIONES_DETALLES ADD COLUMN LONGITUD VARCHAR(20);
