------------------------------------------------------------------------------------------------------------------------
-- TABLE GESTION_CENTROS.TM_PROVEEDORES_TIPOS
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE GESTION_CENTROS.TM_PROVEEDORES_TIPOS (
    ID BIGINT NOT NULL,
    DENOMINACION VARCHAR(100) NOT NULL,
    OBSERVACIONES VARCHAR(200),
    ACTIVO BOOLEAN NOT NULL,
    CONSTRAINT TM_PROVEEDORES_TIPOS_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.TM_PROVEEDORES_TIPOS.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.TM_PROVEEDORES_TIPOS.DENOMINACION IS 'Denominación del tipo de proveedor';
COMMENT ON COLUMN GESTION_CENTROS.TM_PROVEEDORES_TIPOS.OBSERVACIONES IS 'Observaciones sobre el tipo de proveedor';
COMMENT ON COLUMN GESTION_CENTROS.TM_PROVEEDORES_TIPOS.ACTIVO IS 'False - No activo, True -  Activo';

------------------------------------------------------------------------------------------------------------------------
-- TABLE GESTION_CENTROS.TM_PERIODICIDAD_GASTO
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE GESTION_CENTROS.TM_PERIODICIDAD_GASTO (
ID BIGINT NOT NULL,
DENOMINACION VARCHAR(100) NOT NULL,
OBSERVACIONES VARCHAR(200),
ACTIVO BOOLEAN NOT NULL,
CONSTRAINT TM_PERIODICIDAD_GASTO_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.TM_PERIODICIDAD_GASTO.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.TM_PERIODICIDAD_GASTO.DENOMINACION IS 'Denominación del tipo de periodicidad';
COMMENT ON COLUMN GESTION_CENTROS.TM_PERIODICIDAD_GASTO.OBSERVACIONES IS 'Observaciones sobre el tipo de periodicidad';
COMMENT ON COLUMN GESTION_CENTROS.TM_PERIODICIDAD_GASTO.ACTIVO IS 'False - No activo, True -  Activo';

INSERT INTO GESTION_CENTROS.TM_PERIODICIDAD_GASTO (ID, DENOMINACION, OBSERVACIONES, ACTIVO) VALUES (1, 'Mensual', NULL, TRUE);
INSERT INTO GESTION_CENTROS.TM_PERIODICIDAD_GASTO (ID, DENOMINACION, OBSERVACIONES, ACTIVO) VALUES (2, 'Bimensual', NULL, TRUE);
INSERT INTO GESTION_CENTROS.TM_PERIODICIDAD_GASTO (ID, DENOMINACION, OBSERVACIONES, ACTIVO) VALUES (3, 'Trimestral', NULL, TRUE);
INSERT INTO GESTION_CENTROS.TM_PERIODICIDAD_GASTO (ID, DENOMINACION, OBSERVACIONES, ACTIVO) VALUES (4, 'Cuatrimestral', NULL, TRUE);
INSERT INTO GESTION_CENTROS.TM_PERIODICIDAD_GASTO (ID, DENOMINACION, OBSERVACIONES, ACTIVO) VALUES (5, 'Semestral', NULL, TRUE);
INSERT INTO GESTION_CENTROS.TM_PERIODICIDAD_GASTO (ID, DENOMINACION, OBSERVACIONES, ACTIVO) VALUES (6, 'Anual', NULL, TRUE);

------------------------------------------------------------------------------------------------------------------------
-- TABLE GESTION_CENTROS.PROVEEDORES
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE GESTION_CENTROS.PROVEEDORES (
ID BIGINT NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
CIF VARCHAR(14) NOT NULL,
TIPO_ID BIGINT NOT NULL,
EMAIL VARCHAR(150),
DIRECCION VARCHAR(150),
PERSONA_CONTACTO VARCHAR(250) NOT NULL,
TELEFONO VARCHAR(15),
DETALLES VARCHAR(2000),
DOC_URL VARCHAR(200),
DOC_NOMBRE VARCHAR(150),
DOC_CONTENT_TYPE VARCHAR(50),
PERIODICIDAD_GASTO_ID BIGINT,
GASTO NUMERIC(10,2),
FECHA_INICIO_SERVICIO DATE,
FECHA_FIN_SERVICIO DATE,
FECHA_ALARMA_SERVICIO DATE,
RESPONSABLE_ID BIGINT,
CREADO TIMESTAMP NOT NULL,
CREADO_POR BIGINT NOT NULL,
MODIFICADO TIMESTAMP,
MODIFICADO_POR BIGINT,
CONSTRAINT PROVEEDORES_PK PRIMARY KEY (ID),
FOREIGN KEY (TIPO_ID) REFERENCES GESTION_CENTROS.TM_PROVEEDORES_TIPOS (ID),
FOREIGN KEY (PERIODICIDAD_GASTO_ID) REFERENCES GESTION_CENTROS.TM_PERIODICIDAD_GASTO (ID),
FOREIGN KEY (CREADO_POR) REFERENCES GC2006_RELEASE.PC_USUARIOS (ID),
FOREIGN KEY (MODIFICADO_POR) REFERENCES GC2006_RELEASE.PC_USUARIOS (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.NOMBRE IS 'Nombre del proveedor';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.CIF IS 'CIF del proveedor';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.TIPO_ID IS 'FK: GESTION_CENTROS.TM_PROVEEDORES_TIPO.ID';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.EMAIL IS 'Email del proveedor';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.DIRECCION IS 'Dirección social del proveedor';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.PERSONA_CONTACTO IS 'Persona de contacto del proveedor';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.TELEFONO IS 'Teléfono de contacto del proveedor';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.DETALLES IS 'Observaciones sobre el proveedor';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.DOC_URL IS 'URL donde se almacena el fichero';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.DOC_NOMBRE IS 'Nombre del fichero';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.DOC_CONTENT_TYPE IS 'Content type del fichero';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.PERIODICIDAD_GASTO_ID IS 'FK: GESTION_CENTROS.TM_PERIOCIDIDAD_GASTO.ID';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.GASTO IS 'Cuantía del gasto asociada al proveedor';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.FECHA_INICIO_SERVICIO IS 'Fecha de inicio del servicio';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.FECHA_FIN_SERVICIO IS 'Fecha de fin del servicio';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.FECHA_ALARMA_SERVICIO IS 'Fecha de alarma del servicio';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.RESPONSABLE_ID IS 'FK: GC2006_RELEASE.PC_USUARIOS.ID';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.CREADO IS 'Fecha de creación del proveedor';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.CREADO_POR IS 'FK: GC2006_RELEASE.PC_USUARIOS.ID';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.MODIFICADO IS 'Fecha de última modificación del proveedor';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES.MODIFICADO_POR IS 'FK: GC2006_RELEASE.PC_USUARIOS.ID';

CREATE SEQUENCE GESTION_CENTROS.PROVEEDORES_SEQ MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1;
