------------------------------------------------------------------------------------------------------------------------
-- TABLE GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES (
ID BIGINT NOT NULL,
PROVEEDOR_ID BIGINT NOT NULL,
DELEGACION_ID BIGINT NOT NULL,
CONSTRAINT PROVEEDORES_X_DELEGACIONES_PK PRIMARY KEY (ID),
FOREIGN KEY (PROVEEDOR_ID) REFERENCES GESTION_CENTROS.PROVEEDORES (ID),
FOREIGN KEY (DELEGACION_ID) REFERENCES GC2006_RELEASE.PC_DELEGACIONES (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES.PROVEEDOR_ID IS 'FK: GESTION_CENTROS.PROVEEDORES.ID';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES.DELEGACION_ID IS 'FK: GC2006_RELEASE.PC_DELEGACIONES.ID';

CREATE SEQUENCE GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES_SEQ
MINVALUE 1
MAXVALUE 9999999999999999
INCREMENT BY 1;
