------------------------------------------------------------------------------------------------------------------------
-- TABLE GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES (
ID BIGINT NOT NULL,
PROVEEDOR_ID BIGINT NOT NULL,
DELEGACION_ID BIGINT NOT NULL,
CONSTRAINT PROVEEDORES_X_DELEGACIONES_PK PRIMARY KEY (ID),
FOREIGN KEY (PROVEEDOR_ID) REFERENCES GESTION_CENTROS.PROVEEDORES (ID),
FOREIGN KEY (DELEGACION_ID) REFERENCES GC2006_RELEASE.PC_DELEGACIONES (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES.PROVEEDOR_ID IS 'FK: GESTION_CENTROS.PROVEEDORES.ID';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES.DELEGACION_ID IS 'FK: GC2006_RELEASE.PC_DELEGACIONES.ID';

CREATE SEQUENCE GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES_SEQ
MINVALUE 1
MAXVALUE 9999999999999999
INCREMENT BY 1;


------------------------------------------------------------------------------------------------------------------------
-- TABLE GESTION_CENTROS.TM_DELEGACIONES_TIPOS
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE GESTION_CENTROS.TM_DELEGACIONES_TIPOS (
ID BIGINT NOT NULL,
DENOMINACION VARCHAR(100) NOT NULL,
ACTIVO BOOLEAN NOT NULL,
CONSTRAINT TM_DELEGACIONES_TIPOS_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.TM_DELEGACIONES_TIPOS.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.TM_DELEGACIONES_TIPOS.DENOMINACION IS 'Denominación del tipo de delegación';
COMMENT ON COLUMN GESTION_CENTROS.TM_DELEGACIONES_TIPOS.ACTIVO IS 'Activo: 1 | Inactivo: 0';

------------------------------------------------------------------------------------------------------------------------
-- TABLE GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN (
ID BIGINT NOT NULL,
PROV_X_DELEGACION_ID BIGINT NOT NULL,
DOC_URL VARCHAR(200),
DOC_NOMBRE VARCHAR(150),
DOC_CONTENT_TYPE VARCHAR(100),
DETALLES VARCHAR(2000),
GASTO NUMERIC(10,2),
PERIODICIDAD_GASTO_ID BIGINT,
FECHA_INICIO_SERVICIO DATE,
FECHA_FIN_SERVICIO DATE,
CREADO TIMESTAMP NOT NULL,
CREADO_POR BIGINT NOT NULL,
MODIFICADO TIMESTAMP,
MODIFICADO_POR BIGINT,
CONSTRAINT PROVEEDORES_DETALLES_COMUN_PK PRIMARY KEY (ID),
FOREIGN KEY (PROV_X_DELEGACION_ID) REFERENCES GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES (ID),
FOREIGN KEY (PERIODICIDAD_GASTO_ID) REFERENCES GESTION_CENTROS.TM_PERIODICIDAD_GASTO (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN.PROV_X_DELEGACION_ID IS 'FK: GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES.ID';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN.DOC_URL IS 'URL donde se almacena el fichero';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN.DOC_NOMBRE IS 'Nombre del fichero';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN.DOC_CONTENT_TYPE IS 'Content type del fichero';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN.GASTO IS 'Cuantía del gasto asociada al proveedor';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN.PERIODICIDAD_GASTO_ID IS 'FK: GESTION_CENTROS.TM_PERIOCIDIDAD_GASTO.ID';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN.FECHA_INICIO_SERVICIO IS 'Fecha de inicio del servicio';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN.FECHA_FIN_SERVICIO IS 'Fecha de fin del servicio';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN.CREADO IS 'Fecha de creación del proveedor';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN.CREADO_POR IS 'FK: GC2006_RELEASE.PC_USUARIOS.ID';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN.MODIFICADO IS 'Fecha de última modificación del proveedor';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN.MODIFICADO_POR IS 'FK: GC2006_RELEASE.PC_USUARIOS.ID';

CREATE SEQUENCE GESTION_CENTROS.PROVEEDORES_DETALLES_COMUN_SEQ
MINVALUE 1
MAXVALUE 9999999999999999
INCREMENT BY 1;

------------------------------------------------------------------------------------------------------------------------
-- Insert data
------------------------------------------------------------------------------------------------------------------------

-- GESTION_CENTROS.TM_DELEGACIONES_TIPOS
INSERT INTO GESTION_CENTROS.TM_DELEGACIONES_TIPOS (id, denominacion, activo)
VALUES (1, 'DELEGACION', true);

INSERT INTO GESTION_CENTROS.TM_DELEGACIONES_TIPOS (id, denominacion, activo)
VALUES (2, 'CENTRO MEDICO', true);

INSERT INTO GESTION_CENTROS.TM_DELEGACIONES_TIPOS (id, denominacion, activo)
VALUES (3, 'OTROS', true);


------------------------------------------------------------------------------------------------------------------------
-- Alter tables
------------------------------------------------------------------------------------------------------------------------

-- GC2006_RELEASE.PC_DELEGACIONES
ALTER TABLE GC2006_RELEASE.PC_DELEGACIONES RENAME COLUMN TIPO TO TIPO_ID;

ALTER TABLE GC2006_RELEASE.PC_DELEGACIONES ALTER COLUMN TIPO_ID SET DATA TYPE BIGINT;

ALTER TABLE GC2006_RELEASE.PC_DELEGACIONES ADD CONSTRAINT DELEGACIONES_TIPOS_FK
FOREIGN KEY (TIPO_ID) REFERENCES GESTION_CENTROS.TM_DELEGACIONES_TIPOS (ID);

-- */*EJECUTAR*/*

alter table gestion_centros.proveedores drop column doc_url;
alter table gestion_centros.proveedores drop column doc_nombre;
alter table gestion_centros.proveedores drop column doc_content_type;
alter table gestion_centros.proveedores drop column fecha_inicio;
alter table gestion_centros.proveedores drop column fecha_fin;

-- REPASAR MAS COLUMNAS DE PROVEEDORES
