------------------------------------------------------------------------------------------------------------------------
-- GESTION_CENTROS.TM_TIPOS_ATRIBUTOS
------------------------------------------------------------------------------------------------------------------------

CREATE TABLE GESTION_CENTROS.TM_TIPOS_ATRIBUTOS (
ID BIGINT NOT NULL,
COMPONENTE VARCHAR(50) NOT NULL,
TIPO VARCHAR(50),
TIPO_DATO VARCHAR(50) NOT NULL,
CONSTRAINT TM_TIPOS_ATRIBUTOS_PK PRIMARY KEY (ID)
);

INSERT INTO GESTION_CENTROS.TM_TIPOS_ATRIBUTOS (ID, COMPONENTE, TIPO, TIPO_DATO)
VALUES (1, 'input', 'text', 'text');
INSERT INTO GESTION_CENTROS.TM_TIPOS_ATRIBUTOS (ID, COMPONENTE, TIPO, TIPO_DATO)
VALUES (2, 'input', 'number', 'number');
INSERT INTO GESTION_CENTROS.TM_TIPOS_ATRIBUTOS (ID, COMPONENTE, TIPO, TIPO_DATO)
VALUES (3, 'input', 'date', 'date');
INSERT INTO GESTION_CENTROS.TM_TIPOS_ATRIBUTOS (ID, COMPONENTE, TIPO, TIPO_DATO)
VALUES (4, 'textarea', null, 'text');
INSERT INTO GESTION_CENTROS.TM_TIPOS_ATRIBUTOS (ID, COMPONENTE, TIPO, TIPO_DATO)
VALUES (5, 'radiobutton', null, 'number');

------------------------------------------------------------------------------------------------------------------------
-- GESTION_CENTROS.CONF_PROVEEDORES_DETALLES
------------------------------------------------------------------------------------------------------------------------

CREATE TABLE GESTION_CENTROS.CONF_PROVEEDORES_DETALLES (
ID BIGINT NOT NULL,
TIPO_PROVEEDOR_ID BIGINT NOT NULL,
TIPO_ATRIBUTO_ID BIGINT NOT NULL,
ETIQUETA VARCHAR(50) NOT NULL,
ORDEN INT NOT NULL,
-- MAX_LENGTH
-- REQUIRED
CONSTRAINT CONF_PROVEEDORES_DETALLES_PK PRIMARY KEY (ID),
FOREIGN KEY (TIPO_ID) REFERENCES GESTION_CENTROS.TM_PROVEEDORES_TIPOS (ID),
FOREIGN KEY (TIPO_ATRIBUTO_ID) REFERENCES GESTION_CENTROS.TM_TIPOS_ATRIBUTOS (ID)
);

INSERT INTO GESTION_CENTROS.CONF_PROVEEDORES_DETALLES (ID, TIPO_PROVEEDOR_ID, TIPO_ATRIBUTO_ID, ETIQUETA, ORDEN)
VALUES (1, 1, 2, 'Precio/Hora', 1);
INSERT INTO GESTION_CENTROS.CONF_PROVEEDORES_DETALLES (ID, TIPO_PROVEEDOR_ID, TIPO_ATRIBUTO_ID, ETIQUETA, ORDEN)
VALUES (2, 1, 2, 'Precio/Hora extra', 2);
INSERT INTO GESTION_CENTROS.CONF_PROVEEDORES_DETALLES (ID, TIPO_PROVEEDOR_ID, TIPO_ATRIBUTO_ID, ETIQUETA, ORDEN)
VALUES (3, 1, 5, 'Fungible', 3);
INSERT INTO GESTION_CENTROS.CONF_PROVEEDORES_DETALLES (ID, TIPO_PROVEEDOR_ID, TIPO_ATRIBUTO_ID, ETIQUETA, ORDEN)
VALUES (4, 1, 5, 'Limpieza de cristales', 4);
INSERT INTO GESTION_CENTROS.CONF_PROVEEDORES_DETALLES (ID, TIPO_PROVEEDOR_ID, TIPO_ATRIBUTO_ID, ETIQUETA, ORDEN)
VALUES (5, 1, 5, 'Limpieza UM', 5);

------------------------------------------------------------------------------------------------------------------------
-- GESTION_CENTROS.PROVEEDORES_DETALLES
------------------------------------------------------------------------------------------------------------------------

CREATE TABLE GESTION_CENTROS.PROVEEDORES_DETALLES (
ID BIGINT NOT NULL,
PROV_DEL_ID BIGINT NOT NULL,
CONF_PROV_DETALLE_ID BIGINT NOT NULL,
CONF_PROV_DETALLE_VALOR TEXT,
CONSTRAINT PROVEEDORES_DETALLES_PK PRIMARY KEY (ID),
FOREIGN KEY (PROV_DEL_ID) REFERENCES GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES (ID),
FOREIGN KEY (CONF_PROV_DETALLE_ID) REFERENCES GESTION_CENTROS.CONF_PROVEEDORES_DETALLES (ID)
);
