------------------------------------------------------------------------------------------------------------------------
-- GESTION_CENTROS.TM_TIPOS_ATRIBUTOS
------------------------------------------------------------------------------------------------------------------------

CREATE TABLE GESTION_CENTROS.TM_TIPOS_ATRIBUTOS (
ID BIGINT NOT NULL,
COMPONENTE VARCHAR(50) NOT NULL,
TIPO VARCHAR(50),
TIPO_DATO VARCHAR(50) NOT NULL,
CONSTRAINT TM_TIPOS_ATRIBUTOS_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.TM_TIPOS_ATRIBUTOS.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.TM_TIPOS_ATRIBUTOS.COMPONENTE IS 'Tipo de componente en el html';
COMMENT ON COLUMN GESTION_CENTROS.TM_TIPOS_ATRIBUTOS.TIPO IS 'Tipo de componente';
COMMENT ON COLUMN GESTION_CENTROS.TM_TIPOS_ATRIBUTOS.TIPO_DATO IS 'Tipo de valor del componente';

INSERT INTO GESTION_CENTROS.TM_TIPOS_ATRIBUTOS (ID, COMPONENTE, TIPO, TIPO_DATO)
VALUES (1, 'input', 'text', 'text');
INSERT INTO GESTION_CENTROS.TM_TIPOS_ATRIBUTOS (ID, COMPONENTE, TIPO, TIPO_DATO)
VALUES (2, 'input', 'number', 'number');
INSERT INTO GESTION_CENTROS.TM_TIPOS_ATRIBUTOS (ID, COMPONENTE, TIPO, TIPO_DATO)
VALUES (3, 'input', 'date', 'date');
INSERT INTO GESTION_CENTROS.TM_TIPOS_ATRIBUTOS (ID, COMPONENTE, TIPO, TIPO_DATO)
VALUES (4, 'textarea', null, 'text');
INSERT INTO GESTION_CENTROS.TM_TIPOS_ATRIBUTOS (ID, COMPONENTE, TIPO, TIPO_DATO)
VALUES (5, 'radiobutton', null, 'number');

------------------------------------------------------------------------------------------------------------------------
-- GESTION_CENTROS.CONF_PROVEEDORES_DETALLES
------------------------------------------------------------------------------------------------------------------------

CREATE TABLE GESTION_CENTROS.CONF_PROVEEDORES_DETALLES (
ID BIGINT NOT NULL,
TIPO_PROVEEDOR_ID BIGINT NOT NULL,
TIPO_ATRIBUTO_ID BIGINT NOT NULL,
ETIQUETA VARCHAR(50) NOT NULL,
ORDEN INT NOT NULL,
-- MAX_LENGTH
-- REQUIRED
CONSTRAINT CONF_PROVEEDORES_DETALLES_PK PRIMARY KEY (ID),
FOREIGN KEY (TIPO_PROVEEDOR_ID) REFERENCES GESTION_CENTROS.TM_PROVEEDORES_TIPOS (ID),
FOREIGN KEY (TIPO_ATRIBUTO_ID) REFERENCES GESTION_CENTROS.TM_TIPOS_ATRIBUTOS (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.CONF_PROVEEDORES_DETALLES.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.CONF_PROVEEDORES_DETALLES.TIPO_PROVEEDOR_ID IS 'FK: GESTION_CENTROS.TM_PROVEEDORES_TIPOS.ID';
COMMENT ON COLUMN GESTION_CENTROS.CONF_PROVEEDORES_DETALLES.TIPO_ATRIBUTO_ID IS 'FK: GESTION_CENTROS.TM_TIPOS_ATRIBUTOS.ID';
COMMENT ON COLUMN GESTION_CENTROS.CONF_PROVEEDORES_DETALLES.ETIQUETA IS 'Atributo del proveedor';
COMMENT ON COLUMN GESTION_CENTROS.CONF_PROVEEDORES_DETALLES.ORDEN IS 'Orden por el que se mostrará en pantalla';

INSERT INTO GESTION_CENTROS.CONF_PROVEEDORES_DETALLES (ID, TIPO_PROVEEDOR_ID, TIPO_ATRIBUTO_ID, ETIQUETA, ORDEN)
VALUES (1, 1, 2, 'Precio/Hora', 1);
INSERT INTO GESTION_CENTROS.CONF_PROVEEDORES_DETALLES (ID, TIPO_PROVEEDOR_ID, TIPO_ATRIBUTO_ID, ETIQUETA, ORDEN)
VALUES (2, 1, 2, 'Precio/Hora extra', 2);
INSERT INTO GESTION_CENTROS.CONF_PROVEEDORES_DETALLES (ID, TIPO_PROVEEDOR_ID, TIPO_ATRIBUTO_ID, ETIQUETA, ORDEN)
VALUES (3, 1, 5, 'Fungible', 3);
INSERT INTO GESTION_CENTROS.CONF_PROVEEDORES_DETALLES (ID, TIPO_PROVEEDOR_ID, TIPO_ATRIBUTO_ID, ETIQUETA, ORDEN)
VALUES (4, 1, 5, 'Limpieza de cristales', 4);
INSERT INTO GESTION_CENTROS.CONF_PROVEEDORES_DETALLES (ID, TIPO_PROVEEDOR_ID, TIPO_ATRIBUTO_ID, ETIQUETA, ORDEN)
VALUES (5, 1, 5, 'Limpieza UM', 5);

------------------------------------------------------------------------------------------------------------------------
-- GESTION_CENTROS.PROVEEDORES_DETALLES
------------------------------------------------------------------------------------------------------------------------

CREATE TABLE GESTION_CENTROS.PROVEEDORES_DETALLES (
ID BIGINT NOT NULL,
PROV_DEL_ID BIGINT NOT NULL,
CONF_PROV_DETALLE_ID BIGINT NOT NULL,
CONF_PROV_DETALLE_VALOR TEXT,
CONSTRAINT PROVEEDORES_DETALLES_PK PRIMARY KEY (ID),
FOREIGN KEY (PROV_DEL_ID) REFERENCES GESTION_CENTROS.PROVEEDORES_X_DELEGACIONES (ID),
FOREIGN KEY (CONF_PROV_DETALLE_ID) REFERENCES GESTION_CENTROS.CONF_PROVEEDORES_DETALLES (ID)
);

COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES.ID IS 'Primary key de la tabla';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES.PROV_DEL_ID IS 'FK: GESTION_CENTROS.PROVEEDORES_X_DELEGACION.ID';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES.CONF_PROV_DETALLE_ID IS 'FK: GESTION_CENTROS.CONF_PROVEEDORES_DETALLES.ID';
COMMENT ON COLUMN GESTION_CENTROS.PROVEEDORES_DETALLES.CONF_PROV_DETALLE_VALOR IS 'Valor del campo';


CREATE SEQUENCE GESTION_CENTROS.PROVEEDORES_DETALLES_SEQ
MINVALUE 1
MAXVALUE 9999999999999999
INCREMENT BY 1;
